name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: step06_SpringDataJPA

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: step06_SpringDataJPA

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: springboot-jar
        path: step06_SpringDataJPA/build/libs/*.jar
