name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Grant execute permission
      run: chmod +x gradlew
      working-directory: step06_SpringDataJPA

    - name: Build Project
      run: ./gradlew build
      working-directory: step06_SpringDataJPA

    - name: Deploy with Docker
      run: |
        docker stop myapp || true
        docker rm myapp || true
        docker build -t myapp .
        docker run -d -p 8080:8080 --name myapp myapp
      working-directory: step06_SpringDataJPA
